# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='user.proto',
  package='airspan_challenge',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nuser.proto\x12\x11\x61irspan_challenge\"Y\n\x0bUserDetails\x12\x12\n\nfirst_name\x18\x01 \x02(\t\x12\x11\n\tlast_name\x18\x02 \x02(\t\x12\r\n\x05\x65mail\x18\x03 \x02(\t\x12\x14\n\x0cphone_number\x18\x04 \x01(\t\"G\n\x04User\x12\n\n\x02id\x18\x01 \x02(\t\x12\x33\n\x0bUserDetails\x18\x02 \x02(\x0b\x32\x1e.airspan_challenge.UserDetails\"0\n\x05Users\x12\'\n\x06people\x18\x01 \x03(\x0b\x32\x17.airspan_challenge.User\"\x18\n\nUserDelete\x12\n\n\x02id\x18\x01 \x02(\t\"d\n\nUserUpdate\x12\x12\n\nfirst_name\x18\x01 \x01(\t\x12\x11\n\tlast_name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\n\n\x02id\x18\x04 \x02(\t\x12\x14\n\x0cphone_number\x18\x05 \x01(\t\"\x96\x01\n\x10\x45\x64itUserResponse\x12K\n\x06result\x18\x01 \x02(\x0e\x32\x32.airspan_challenge.EditUserResponse.EditUserResult:\x07SUCCESS\"5\n\x0e\x45\x64itUserResult\x12\x08\n\x04\x46\x41IL\x10\x00\x12\x0b\n\x07SUCCESS\x10\x01\x12\x0c\n\x08NOTEXIST\x10\x02\"\xad\x01\n\x0eWrapperMessage\x12\x13\n\x0b\x63ommonField\x18\x01 \x02(\x03\x12+\n\x02m1\x18\x02 \x01(\x0b\x32\x1d.airspan_challenge.UserUpdateH\x00\x12%\n\x02m2\x18\x03 \x01(\x0b\x32\x17.airspan_challenge.UserH\x00\x12+\n\x02m3\x18\x04 \x01(\x0b\x32\x1d.airspan_challenge.UserDeleteH\x00\x42\x05\n\x03msg'
)



_EDITUSERRESPONSE_EDITUSERRESULT = _descriptor.EnumDescriptor(
  name='EditUserResult',
  full_name='airspan_challenge.EditUserResponse.EditUserResult',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FAIL', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='NOTEXIST', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=473,
  serialized_end=526,
)
_sym_db.RegisterEnumDescriptor(_EDITUSERRESPONSE_EDITUSERRESULT)


_USERDETAILS = _descriptor.Descriptor(
  name='UserDetails',
  full_name='airspan_challenge.UserDetails',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='first_name', full_name='airspan_challenge.UserDetails.first_name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='last_name', full_name='airspan_challenge.UserDetails.last_name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='email', full_name='airspan_challenge.UserDetails.email', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='phone_number', full_name='airspan_challenge.UserDetails.phone_number', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=122,
)


_USER = _descriptor.Descriptor(
  name='User',
  full_name='airspan_challenge.User',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='airspan_challenge.User.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='UserDetails', full_name='airspan_challenge.User.UserDetails', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=124,
  serialized_end=195,
)


_USERS = _descriptor.Descriptor(
  name='Users',
  full_name='airspan_challenge.Users',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='people', full_name='airspan_challenge.Users.people', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=197,
  serialized_end=245,
)


_USERDELETE = _descriptor.Descriptor(
  name='UserDelete',
  full_name='airspan_challenge.UserDelete',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='airspan_challenge.UserDelete.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=247,
  serialized_end=271,
)


_USERUPDATE = _descriptor.Descriptor(
  name='UserUpdate',
  full_name='airspan_challenge.UserUpdate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='first_name', full_name='airspan_challenge.UserUpdate.first_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='last_name', full_name='airspan_challenge.UserUpdate.last_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='email', full_name='airspan_challenge.UserUpdate.email', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='id', full_name='airspan_challenge.UserUpdate.id', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='phone_number', full_name='airspan_challenge.UserUpdate.phone_number', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=273,
  serialized_end=373,
)


_EDITUSERRESPONSE = _descriptor.Descriptor(
  name='EditUserResponse',
  full_name='airspan_challenge.EditUserResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='airspan_challenge.EditUserResponse.result', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _EDITUSERRESPONSE_EDITUSERRESULT,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=376,
  serialized_end=526,
)


_WRAPPERMESSAGE = _descriptor.Descriptor(
  name='WrapperMessage',
  full_name='airspan_challenge.WrapperMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='commonField', full_name='airspan_challenge.WrapperMessage.commonField', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='m1', full_name='airspan_challenge.WrapperMessage.m1', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='m2', full_name='airspan_challenge.WrapperMessage.m2', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='m3', full_name='airspan_challenge.WrapperMessage.m3', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='msg', full_name='airspan_challenge.WrapperMessage.msg',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=529,
  serialized_end=702,
)

_USER.fields_by_name['UserDetails'].message_type = _USERDETAILS
_USERS.fields_by_name['people'].message_type = _USER
_EDITUSERRESPONSE.fields_by_name['result'].enum_type = _EDITUSERRESPONSE_EDITUSERRESULT
_EDITUSERRESPONSE_EDITUSERRESULT.containing_type = _EDITUSERRESPONSE
_WRAPPERMESSAGE.fields_by_name['m1'].message_type = _USERUPDATE
_WRAPPERMESSAGE.fields_by_name['m2'].message_type = _USER
_WRAPPERMESSAGE.fields_by_name['m3'].message_type = _USERDELETE
_WRAPPERMESSAGE.oneofs_by_name['msg'].fields.append(
  _WRAPPERMESSAGE.fields_by_name['m1'])
_WRAPPERMESSAGE.fields_by_name['m1'].containing_oneof = _WRAPPERMESSAGE.oneofs_by_name['msg']
_WRAPPERMESSAGE.oneofs_by_name['msg'].fields.append(
  _WRAPPERMESSAGE.fields_by_name['m2'])
_WRAPPERMESSAGE.fields_by_name['m2'].containing_oneof = _WRAPPERMESSAGE.oneofs_by_name['msg']
_WRAPPERMESSAGE.oneofs_by_name['msg'].fields.append(
  _WRAPPERMESSAGE.fields_by_name['m3'])
_WRAPPERMESSAGE.fields_by_name['m3'].containing_oneof = _WRAPPERMESSAGE.oneofs_by_name['msg']
DESCRIPTOR.message_types_by_name['UserDetails'] = _USERDETAILS
DESCRIPTOR.message_types_by_name['User'] = _USER
DESCRIPTOR.message_types_by_name['Users'] = _USERS
DESCRIPTOR.message_types_by_name['UserDelete'] = _USERDELETE
DESCRIPTOR.message_types_by_name['UserUpdate'] = _USERUPDATE
DESCRIPTOR.message_types_by_name['EditUserResponse'] = _EDITUSERRESPONSE
DESCRIPTOR.message_types_by_name['WrapperMessage'] = _WRAPPERMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UserDetails = _reflection.GeneratedProtocolMessageType('UserDetails', (_message.Message,), {
  'DESCRIPTOR' : _USERDETAILS,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:airspan_challenge.UserDetails)
  })
_sym_db.RegisterMessage(UserDetails)

User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), {
  'DESCRIPTOR' : _USER,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:airspan_challenge.User)
  })
_sym_db.RegisterMessage(User)

Users = _reflection.GeneratedProtocolMessageType('Users', (_message.Message,), {
  'DESCRIPTOR' : _USERS,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:airspan_challenge.Users)
  })
_sym_db.RegisterMessage(Users)

UserDelete = _reflection.GeneratedProtocolMessageType('UserDelete', (_message.Message,), {
  'DESCRIPTOR' : _USERDELETE,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:airspan_challenge.UserDelete)
  })
_sym_db.RegisterMessage(UserDelete)

UserUpdate = _reflection.GeneratedProtocolMessageType('UserUpdate', (_message.Message,), {
  'DESCRIPTOR' : _USERUPDATE,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:airspan_challenge.UserUpdate)
  })
_sym_db.RegisterMessage(UserUpdate)

EditUserResponse = _reflection.GeneratedProtocolMessageType('EditUserResponse', (_message.Message,), {
  'DESCRIPTOR' : _EDITUSERRESPONSE,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:airspan_challenge.EditUserResponse)
  })
_sym_db.RegisterMessage(EditUserResponse)

WrapperMessage = _reflection.GeneratedProtocolMessageType('WrapperMessage', (_message.Message,), {
  'DESCRIPTOR' : _WRAPPERMESSAGE,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:airspan_challenge.WrapperMessage)
  })
_sym_db.RegisterMessage(WrapperMessage)


# @@protoc_insertion_point(module_scope)
